### ISSUE TITLE
建议增加一个模块管理依赖包

### ISSUE THREAD

**Issue by jic138168** [bbossgroups/bboss-elasticsearch#10]
增加dependencies 管理依赖包
![image](https://user-images.githubusercontent.com/35680692/64591187-cea92180-d3db-11e9-804f-178403eee10c.png)

**Comment by yin-bp** [comment]
使用bboss只要一个maven坐标就可以了：

  <dependency>
            <groupId>com.bbossgroups.plugins</groupId>
            <artifactId>bboss-elasticsearch-spring-boot-starter</artifactId>
            <version>5.8.8</version>
        </dependency>
