### ISSUE TITLE
sql查询日期处理问题

### ISSUE THREAD

**Issue by tanghouhong** [bbossgroups/bboss-elasticsearch#11]
关于sql查询，日期类型问题，elasticsearch返回的columns{
            "name":"createTime",
            "type":"datetime"
        }中关于type描述信息是datetime
日期判断函数如下，无法准确判定匹配会导致转换错误
public static boolean isDateType(ColumnMeta columnMeta){
     return columnMeta.getType().equals("date");
}

**Comment by yin-bp** [comment]
bug已经处理，下一个版本发布，请关注

**Comment by yin-bp** [comment]
v5.8.9 功能改进
1.改进检索Meta数据：增加seqNo和primaryTerm属性。

2.includeTypeName配置默认设置为false

3.BUG fixed: sql查询日期处理问题 #11

https://esdoc.bbossgroups.com/#/changelog

更新升级文档：修改Maven坐标版本号为5.8.9即可
https://esdoc.bbossgroups.com/#/quickstart
