### ISSUE TITLE
基于时间戳的同步问题

### ISSUE THREAD

**Issue by SimpleYj** [bbossgroups/bboss-elasticsearch#16]
5.8.9版本 在数据库中添加3条记录，第一次同步完成后increament_tab表中记录的lastvalue值为20191026104545(这是我最后一条数据的时间)lastvaluetype=1(基于时间戳的) 我在数据库中增加一条数据,在点同步～ 数据无法同步(后台未报错,lastvalue依然是20191026104545) ，

修改成NUMBER_TYPE 基于ID自增的测试 可通过

**Comment by yin-bp** [comment]
@SimpleYj，可升级版本到5.9.0，最新demo下载：
https://github.com/bbossgroups/db-elasticsearch-tool
