### ISSUE TITLE
ESDatas如何映射到多路径的字段？

### ISSUE THREAD

**Issue by dik111** [bbossgroups/bboss-elasticsearch#18]
您好，比如说这个log.file.path应该怎么样在实体类中定义呢？
![QQ图片20191111174330](https://user-images.githubusercontent.com/34541162/68577440-0fd8b300-04ab-11ea-852c-50690348c20c.png)

`@JsonProperty("log.file.path")
    private String path;`
这样好像不太行

**Comment by yin-bp** [comment]
@dik111,这种数据层次有点深，要么简化数据结构，要么在你的对象里面定义一个嵌套的对象进行映射：
```
private Log log;

class Log{
 File file;
}
class File{
String path；
}
```

或者在对象里面定义一个Map对象即可：
`private Map log;`

**Comment by dik111** [comment]
> private Map log;

private Map log; 可以了！ 感谢
