### ISSUE TITLE
5.0.8.8模板缓存语句导致内存溢出，新版本是否解决了？

### ISSUE THREAD

**Issue by ableYang123** [bbossgroups/bboss-elasticsearch#19]
你好！ 我们生产环境在使用5.0.8.8版本，前段时间发现系统堆内存溢出奔溃（因疫情两个月未发版重启）。溢出对象为HashWeakMap$Entry数组，对象达到100w以上，存储内容为渲染语句

**Comment by yin-bp** [comment]
> 你好！ 我们生产环境在使用5.0.8.8版本，前段时间发现系统堆内存溢出奔溃（因疫情两个月未发版重启）。溢出对象为HashWeakMap$Entry数组，对象达到100w以上，存储内容为渲染语句

具体的错误日志发一下

**Comment by ableYang123** [comment]
我们生产的日志不能发送，使用的是springboot套件集成

**Comment by yin-bp** [comment]
1.首先升级到最新版本，最新版本参【[bboss的版本变更记录](https://esdoc.bbossgroups.com/#/changelog)】

2.如果是模板解析溢出，可以参考优化文档：
https://esdoc.bbossgroups.com/#/question-answer?id=%e9%97%ae%e9%a2%985-the-number-of-real-dsl-cache-records-exceeded-the-maximum-cache-size-n-allowed-by-dsl-structure-cache
