### ISSUE TITLE
兼容elasticsearch 7.6的updateDocument的问题

### ISSUE THREAD

**Issue by wushengqiang** [bbossgroups/bboss-elasticsearch#20]
你好!在开发的过程中,我的elasticsearch 版本是7.6,发现updateDocument时出现异常,发送的接口是indexName/_doc/_update/documentId,elasticsearch 7.6部分更新的接口是indexName/_update/document

**Comment by yin-bp** [comment]
> 你好!在开发的过程中,我的elasticsearch 版本是7.6,发现updateDocument时出现异常,发送的接口是indexName/_doc/_update/documentId,elasticsearch 7.6部分更新的接口是indexName/_update/document

最新版本不存在这个问题，建议参考下面的文档，升级bboss到最新版本：
https://esdoc.bbossgroups.com/#/changelog

**Comment by wushengqiang** [comment]
我使用的是这个接口 public String updateDocument(Object documentId,Object params) throws ElasticSearchException; 来修改,结果还是报了{"error":"no handler found for uri [/classroom/_doc/_update/3] and method [POST]"} 这个错误,bboss版本是6.0.5

**Comment by yin-bp** [comment]
> 我使用的是这个接口 public String updateDocument(Object documentId,Object params) throws ElasticSearchException; 来修改,结果还是报了{"error":"no handler found for uri [/classroom/_doc/_update/3] and method [POST]"} 这个错误,bboss版本是6.0.5

不可能的，只要是elasticsearch 7以上的版本，都不是这样的地址，你可以自己debug以下方法：
org.frameworkset.elasticsearch.client.BuildTool

public static String buildUpdatePathUrlMeta(String index ,String indexType,Object params,ClientOptions clientOptions,ClassUtil.ClassInfo beanInfo,boolean uper7)
