### ISSUE TITLE
spring boot ElasticSearch Template [xxxx]@esmapper/search.xml 未定义. at stopping

### ISSUE THREAD

**Issue by caozhiyuan** [bbossgroups/bboss-elasticsearch#21]
spring boot ElasticSearch Template [xxxx]@esmapper/search.xml 未定义. at stopping,
can run shutdown hooks after spring bean destroy?

{
  "file": "ESTemplateHelper.java",
  "method": "evalTemplate",
  "line": 53,
  "class": "org.frameworkset.elasticsearch.template.ESTemplateHelper"
},
{
  "file": "ConfigRestClientUtil.java",
  "method": "searchList",
  "line": 609,
  "class": "org.frameworkset.elasticsearch.client.ConfigRestClientUtil"
},

**Comment by caozhiyuan** [comment]
i add this code , seems ok.
```

    @Override
    public void destroy() {
        BaseApplicationContext.shutdown();
        log.info("BBoss BaseApplicationContext.shutdown");
    }

    @Override
    public void afterPropertiesSet() {
        try {
            Field shutdownHookField = BaseApplicationContext.class.getDeclaredField("shutdownHook");
            if (shutdownHookField != null) {
                shutdownHookField.setAccessible(true);
                Object thread = shutdownHookField.get(null);
                Runtime.getRuntime().removeShutdownHook((Thread) thread);
            }
        } catch (Exception ex) {
            log.error("EsConfig afterPropertiesSet error", ex);
        }
    }

```

**Comment by caozhiyuan** [comment]
@yin-bp help

**Comment by yin-bp** [comment]
应用没有结束，不能shutdown，去掉吧

**Comment by caozhiyuan** [comment]
@yin-bp BaseApplicationContext shutdownHook run before BBossESStarter bean destroy , and when handle http request, get ClientInterface call searchList raise  ElasticSearch Template [xxxx]@esmapper/search.xml error

**Comment by luger1990** [comment]
> @yin-bp BaseApplicationContext shutdownHook run before BBossESStarter bean destroy , and when handle http request, get ClientInterface call searchList raise ElasticSearch Template [xxxx]@esmapper/search.xml error

How do you fix the issue?
