### ISSUE TITLE
bean属性的别名问题

### ISSUE THREAD

**Issue by suiyueranzly** [bbossgroups/bboss-elasticsearch#22]
您好，请问当前是否支持名称映射的操作，
比如es中查询出的数据列名为abc
我想映射到实体类的bcd属性上，大概查了一下文档，没有找到相关的说明
麻烦了

**Comment by yin-bp** [comment]
当elasticsearch索引表字段名称和java bean的字段名称不一致的情况下，采用@JsonProperty注解用来定义elasticsearch和java bean的field名称转换映射关系，使用实例如下：

@JsonProperty("max_score")
private Double maxScore;

https://esdoc.bbossgroups.com/#/development
![image](https://user-images.githubusercontent.com/526867/80308885-1615de00-8804-11ea-8a11-6412775f054a.png)
