### ISSUE TITLE
Kerberos认证

### ISSUE THREAD

**Issue by xuhuanfeng** [bbossgroups/bboss-elasticsearch#23]
Hello

请问目前是否有支持Kerberos认证的计划呢？

或者目前是否有方式可以注入自定义的Http Client呢？我看源码里头的ClientConfiguration的getHttpClient方法为final实现，似乎无法自行注入自己实现的HttpClient，(如果支持的话，我们自己应该可以尝试下实现简单的Kerberos认证)

**Comment by yin-bp** [comment]
计划在下一版本提供Http Client扩展机制，这样即可自行定制设置认证机制

**Comment by xuhuanfeng** [comment]
明白，也就是目前来说，是不支持自己扩展HttpClient？

那么，请问下，下一版本计划大概是什么时候发布呢？

**Comment by yin-bp** [comment]
扩展完成后即可发布

**Comment by yin-bp** [comment]
@xuhuanfeng 功能已经实现，升级到bboss最新的5.1.2即可，使用参考文档：2.aws签名认证机制实现
https://esdoc.bbossgroups.com/#/aws-elasticsearch-config

**Comment by yin-bp** [comment]
bboss kerberos认证对接参考文档：
https://esdoc.bbossgroups.com/#/development?id=_212-kerberos%e8%ae%a4%e8%af%81%e9%85%8d%e7%bd%ae
