### ISSUE TITLE
Amazon OpenSearch 

### ISSUE THREAD

**Issue by HaiTao-G** [bbossgroups/bboss-elasticsearch#53]
想请问一下,该框架是否支持亚马逊的Amazon OpenSearch搜索引擎呢.(OpenSearch 是 fork 自 Elasticsearch 7.10.2 的开源搜索和分析引擎。)

**Comment by yin-bp** [comment]
没有做过与Amazon OpenSearch对接尝试，欢迎验证测试，参考文档：
https://esdoc.bbossgroups.com/#/quickstart

如有问题可以进行反馈交流，qq群：21220580

**Comment by beijingcn** [comment]
链接OpenSearch  初始化时获取版本号 为 2.3.0，判断版本小于7  ， 所以后续请求会带上 type 则出错。

**Comment by yin-bp** [comment]
@beijingcn 

麻烦提供一下opensearch的连接欢迎信息，以便进行识别处理

**Comment by beijingcn** [comment]
> @beijingcn
> 
> 麻烦提供一下opensearch的连接欢迎信息，以便进行识别处理

如上一个回复

**Comment by beijingcn** [comment]
@yin-bp 如上一个回复

**Comment by yin-bp** [comment]
问题已经修复并提交github
