### ISSUE TITLE
查询结果不支持从stored_fields取数？

### ISSUE THREAD

**Issue by wzqiang1332** [bbossgroups/bboss-elasticsearch#54]
如题，索引的大部分字段使用的store存储，结果查询时无法映射

**Comment by yin-bp** [comment]
Hi,@wzqiang1332
> 如题，索引的大部分字段使用的store存储，结果查询时无法映射

请提供具体的代码、dsl、es mapping结构资料，以及elasticsearch版本信息，否则问题无从下手分析

**Comment by wzqiang1332** [comment]
> 

非常感谢，我是发现store存储的字段无法直接映射到pojo类里面，现在发现有@EsMetaFields的注解可以映射到一个Map，有其他方法映射到pojo属性吗

**Comment by yin-bp** [comment]
> > 
> 
> 非常感谢，我是发现store存储的字段无法直接映射到pojo类里面，现在发现有@EsMetaFields的注解可以映射到一个Map，有其他方法映射到pojo属性吗

暂时没有其他办法，只有注解能做到：
https://esdoc.bbossgroups.com/#/client-annotation
