### ISSUE TITLE
bboss-elasticsearch-rest-jdbc:6.3.0 错误

### ISSUE THREAD

**Issue by jonZ92** [bbossgroups/bboss-elasticsearch#57]
java.lang.IllegalStateException:Connection pool shut down 错误。最新版本有修改这个错误吗？

**Comment by yin-bp** [comment]
> @jonZ92 

可以升级到最新版本，参考文档导入bboss升级：
https://esdoc.bbossgroups.com/#/changelog

如果存在问题，可以检查是否在运行过程中停止了bboss数据源，譬如jvm退出时自动关闭数据源导致

**Comment by jonZ92** [comment]
> > @jonZ92
> 
> 文档可以升级到最新版本，参考导入bboss升级： https://esdoc.bbossgroups.com/#/changelog
> 
> 如果存在问题，可以检查是否在运行过程中停止了bboss数据源，比如jvm退出时自动关闭数据源导致
非常感谢！^_^

**Comment by yin-bp** [comment]
@jonZ92
在最新的6.8.0版本中已经修复了该问题
参考文档导入bboss升级：
https://esdoc.bbossgroups.com/#/changelog
