### ISSUE TITLE
返回数据解析问题

### ISSUE THREAD

**Issue by faquir-sun** [bbossgroups/bboss-elasticsearch#6]
你好，
elasticsearch-sql 查询返回 list<Map>
List<Map> demos = esDatas.getDatas();
sql中有统计字段，需要自己一层层去解析aggregations内容，不能像elasticsearch-sql的界面一样自动解析成列表吗？

**Comment by yin-bp** [comment]
Hi,@faquir-sun,here is an example:
	`
/**
	 * Elasticsearch-SQL插件功能测试方法
	 */
	@Test
	public void testESSQLSearchagg(){
		ClientInterface clientUtil = ElasticSearchHelper.getRestClientUtil();
		ESAggDatas<LongAggHit> esDatas =  //ESDatas包含当前检索的记录集合，最多10条记录，由sql中的limit属性指定
				clientUtil.searchAgg("/_sql",//sql请求
						"select operModule.keyword from dbdemo group by operModule.keyword ", //elasticsearch-sql支持的sql语句
						LongAggHit.class,"operModule.keyword");//返回的文档封装对象类型
		//获取结果对象列表
		List<LongAggHit> demos = esDatas.getAggDatas();

		//获取总记录数
		long totalSize = esDatas.getTotalSize();
		System.out.println(totalSize);
	}
`
