### ISSUE TITLE
spring boot 执行shutdown的时候报错

### ISSUE THREAD

**Issue by luger1990** [bbossgroups/bboss-elasticsearch#60]
错误如下：
```
org.frameworkset.elasticsearch.ElasticSearchException: ElasticSearch Template [prefixWord]@esmapper/esSearchPrefixOther.xml 未定义.
	at org.frameworkset.elasticsearch.template.ESTemplateHelper.evalTemplate(ESTemplateHelper.java:53)
	at org.frameworkset.elasticsearch.client.AbstractConfigRestClientUtil.complateSuggest(AbstractConfigRestClientUtil.java:1002)
```
有遇到过这个问题吗，请问怎么解决。

**Comment by yin-bp** [comment]
@luger1990 这个问题是在哪个版本抛出来的额，可以升级到最新的7.1.1版本
https://esdoc.bbossgroups.com/#/changelog

**Comment by luger1990** [comment]
> @luger1990 这个问题是在哪个版本抛出来的额，可以升级到最新的7.1.1版本 https://esdoc.bbossgroups.com/#/changelog

目前是6.9.6 我们试试最新版

**Comment by luger1990** [comment]
![image](https://github.com/bbossgroups/bboss-elasticsearch/assets/2096878/c802a884-2782-4bba-b125-06f95d23512e)
@yin-bp 最新版还是会报错

**Comment by luger1990** [comment]
![image](https://github.com/bbossgroups/bboss-elasticsearch/assets/2096878/f2d6a567-7e6a-4915-a027-89384931682a)

**Comment by yin-bp** [comment]
改进了一下bboss基础框架，可以下载bboss工程本地构建试试：
https://github.com/bbossgroups/bboss/commit/a9dfb406ce89617195836a935a9e685a4dde0146

优化jvm推出机制：默认关闭jvm退出时注销ioc容器及相关资源：
   只有在启用自动关闭的情况下，才可以在jvm退出时自动关闭和释放资源，否则需要手动调用ShutdownUtil.shutdown()方法释放资源，启用自动释放资源方法：
   java命令行参数
   -DenableShutdownHook=true
   环境变量
   enableShutdownHook=true
   默认关闭字段释放bboss ioc容器资源：enableShutdownHook=false


源码构建指南：
https://esdoc.bbossgroups.com/#/bboss-build

**Comment by luger1990** [comment]
> @luger1990 改进了一下bboss基础框架，可以下载bboss工程本地构建试试： [bbossgroups/bboss@a9dfb40](https://github.com/bbossgroups/bboss/commit/a9dfb406ce89617195836a935a9e685a4dde0146)
> 
> 源码地址 https://github.com/bbossgroups/bboss
> 
> 优化jvm推出机制：默认关闭jvm退出时注销ioc容器及相关资源： 只有在启用自动关闭的情况下，才可以在jvm退出时自动关闭和释放资源，否则需要手动调用ShutdownUtil.shutdown()方法释放资源，启用自动释放资源方法： java命令行参数 -DenableShutdownHook=true 环境变量 enableShutdownHook=true 默认关闭字段释放bboss ioc容器资源：enableShutdownHook=false
> 
> 源码构建指南： https://esdoc.bbossgroups.com/#/bboss-build

明天给反馈

**Comment by luger1990** [comment]
> @luger1990 改进了一下bboss基础框架，可以下载bboss工程本地构建试试： [bbossgroups/bboss@a9dfb40](https://github.com/bbossgroups/bboss/commit/a9dfb406ce89617195836a935a9e685a4dde0146)
> 
> 源码地址 https://github.com/bbossgroups/bboss
> 
> 优化jvm推出机制：默认关闭jvm退出时注销ioc容器及相关资源： 只有在启用自动关闭的情况下，才可以在jvm退出时自动关闭和释放资源，否则需要手动调用ShutdownUtil.shutdown()方法释放资源，启用自动释放资源方法： java命令行参数 -DenableShutdownHook=true 环境变量 enableShutdownHook=true 默认关闭字段释放bboss ioc容器资源：enableShutdownHook=false
> 
> 源码构建指南： https://esdoc.bbossgroups.com/#/bboss-build

@yin-bp 测试没问题了！

**Comment by luger1990** [comment]
@yin-bp 请问什么时候发正式版 我们升级到最新的正式版

**Comment by yin-bp** [comment]
> @yin-bp 请问什么时候发正式版 我们升级到最新的正式版

@luger1990 最近会进行发布
