### ISSUE TITLE
createIndiceMapping(...)和createTemplate(...) 可以直接读取注解吧？

### ISSUE THREAD

**Issue by gumutianqi** [bbossgroups/bboss-elasticsearch#7]
和 Spring-Boot 的集成里面，既然定义了很多注解，例如 ESIndex，Column，Format 等等，那是不是应该把 ESIndex 注解的属性补全，就不用定义索引创建的 xml 了，当然还应该有一个 ESTemplate 的注解用来定义 Template 中的属性；

这样也更容易使用 createIndiceMapping(...)和createTemplate(...)  来维护索引结构等等；

同时使用注解和 XML 来定义索引结构和字段属性说明，还怎么维护 ORM-Mappings 啊；

**Comment by yin-bp** [comment]
对应索引mapping和索引template的管理，bboss是通过xml+dsl的方式来实现的，目前没有提供注解方式的管理方法，具体索引mapping和索引template的管理bboss api使用可以参考文档：
https://esdoc.bbossgroups.com/#/index-indextemplate

es增删改查的参考使用文档：
https://esdoc.bbossgroups.com/#/document-crud
